services:
  app:
    image: food-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/food_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 5246

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: 5246
    ports:
      - "3306:3306"
