services:
  - name: chat-app
    type: web
    repo: https://github.com/katururakesh/full-stack-projects
    branch: main
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://chat_db_e2qk_user:u8aeC0xYX6dQdlb8Wnzh1RovmGgQte0F@dpg-cup3dct6l47c73cijf3g-a/chat_db_e2qk
      - key: SPRING_DATASOURCE_USERNAME
        value: postgres
      - key: SPRING_DATASOURCE_PASSWORD
        value: 783389
    runtime: docker
